### ISSUE TITLE
Doesn't convert 24bit ALAC to FLAC

### ISSUE THREAD

**Issue by Sleek1** [tattwamasi/TeslaTunes#1]
I LOVE your app (THANK YOU) and it saved me a lot of time, but I found a lot of my albums were not copied/converted. It turns out I have over 5000 high resolution ALAC files (24bit and 44.1 / 48 / 88.2 or 96kHz) and the Tesla Model S DOES support 24bit FLAC files. These types of files are getting very popular. Could you enable conversion of ALL ALAC files, including high resolution? It wouldn't kill me if it down converted them to 16bit/44.1kHz but I'd prefer to keep them at full resolution. I'd be happy to send you some 24 bit files to check out if you need them. If I don't get this working, I'll have to try "majorlance's" script posted on the Tesla Motors Club forum. My plan is to simply create 1 playlist with my entire library and convert it with his script. I much prefer your app. Thanks ra-san.

**Comment by tattwamasi** [comment]
Send me a sample of each and I'll add it in (no down converting).  I didn't realize the S supported the 88.2 and 96.  I had originally planned >16bit support, but ran into an issue with the apple library I was using not doing what I expected it to do in order to properly feed the flac library. I have a workaround, but hadn't implemented it.

I was hoping to get time this weekend to get the next version done, which should handle playlists too similar to the way majorlance's applescript does.  Not sure if that timeline works for you, and no promises, but I don't think it'll be a big deal to get those formats supported.  Doing the genre hack in a way that doesn't bug me (I don't want to change the library, even temporarily) will be the hardest part of this coming release.

On the other hand, major lance's script seems to be working well, so if XLD properly handles your files, and you just want to get it done, that's probably a good, fast option.  Either way, if you send me samples, I'll try to get it in the next release, and I hope to be able to do everything the applescript does, plus more, but faster and easier install.

**Comment by Sleek1** [comment]
Sorry, I just saw your reply! It’s been a busy weekend. I’ve attached a few ALAC files to try as promised.

I did find a workaround with major lance’s script. I simply created a smart playlist with all of the High Resolution songs and used his script to fill in what was missing from your app. It’s been 3 days now and had repeated applescript errors, mostly because of the computer not actually going to sleep, but it’s seems display sleep caused a problem. Anyway…

Again, I really appreciate your work on this.

Jeff

https://www.dropbox.com/s/ujnmaw8v6357zxw/HiResALAC.zip?dl=0

On Apr 10, 2015, at 11:37 PM, tattwamasi <notifications@github.com <mailto:notifications@github.com>> wrote:

Send me a sample of each and I'll add it in. I didn't realize the S supported the 88.2 and 96. I had originally planned >16bit support, but ran into an issue with the apple library I was using not doing what I expected it to do in order to properly feed the flac library. I have a workaround, but hadn't implemented it.

I was hoping to get time this weekend to get the next version done, which should handle playlists too similar to the way majorlance's applescript does. Not sure if that timeline works for you, and no promises, but I don't think it'll be a big deal to get those formats supported. Doing the genre hack in a way that doesn't bug me (I don't want to change the library, even temporarily) will be the hardest part of this coming release.

On the other hand, major lance's script seems to be working well, so if XLD properly handles your files, and you just want to get it done, that's probably a good, fast option. Either way, if you send me samples, I'll try to get it in the next release, and I hope to be able to do everything the applescript does, plus more, but faster and easier install.

**Comment by tattwamasi** [comment]
Great I have added support for 20 and 24 bit per sample files. Far as I can see the flac encoder doesn't support 32 bps, but if that's important we can try to find a workaround. 
I have a bit more testing to do but expect to make a release tonight or early tomorrow, if all is well.

**Comment by Sleek1** [comment]
WOW. That’s Awesome. I’ll be your beta tester. I have not seen 32bit files and doubt the Model S Supports them. Many people are using 24bit/192kHz and apparently Model S Supports 192kHz. I downsample my library to 96kHz because my DAC doesn’t support them over USB (and I doubt there is a difference!). Just to be sure, here is a 24/196 file for you to try…

https://www.dropbox.com/s/k935uxa35xkzb1s/6-Get%20Up%20Stand%20Up.flac?dl=0 https://www.dropbox.com/s/k935uxa35xkzb1s/6-Get%20Up%20Stand%20Up.flac?dl=0

Jeff

On Apr 12, 2015, at 1:40 PM, tattwamasi notifications@github.com wrote:

Great I have added support for 20 and 24 bit per sample files. Far as I can see the flac encoder doesn't support 32 bps, but if that's important we can try to find a workaround. 
I have a bit more testing to do but expect to make a release tonight or early tomorrow, if all is well.

**Comment by tattwamasi** [comment]
I tested the 3 files from the dropbox.  They worked fine in the development build I'm currently testing.  None were 192Kz, but if you want to send one to test, I will.  Nothing in my code would prevent it from working, and looks like the FLAC encoder will handle it too.

I just want to add some logic to sanitize the filenames used in the playlist sync support I've added (since the filenames come from the track metadata and could contain illegal characters), and I'll upload a release.  Won't take much time, but not sure when I'll next get a while to work on it - expect it'll be done tonight regardless.

Edit: just re read and saw you included a 192KHz to test.  Will try it.

**Comment by tattwamasi** [comment]
The last file attached was a flac file, not alac, and wasn't 192Khz, but the new release has been posted so go ahead and give it a shot.  Note that instead of your selected source folder being copied directly to the selected destination folder like it was in the last release, it will now be placed in a subdirectory called "Music" at the selected destination folder.  This is because playlists are also supported and things were too cluttered to have the playlist folders interspersed with the music folders.  Now there will be (up to) two folders at the destination - "Music" containing all the music folders and "Playlists" containing all the playlist folders.  I mention this since you've done a lot of copying already - would hate to have you accidentally create a zillion extra copies one level down.

**Comment by Sleek1** [comment]
I tested your app and I can verify that 24 bit up to 192kHz is working great as is your playlist addition.

Thank you for this excellent app.

On Apr 13, 2015, at 12:14 AM, tattwamasi notifications@github.com wrote:

The last file attached was a flac file, not alac, and wasn't 192Khz, but the new release has been posted so go ahead and give it a shot. Note that instead of your selected source folder being copied directly to the selected destination folder like it was in the last release, it will now be placed in a subdirectory called "Music" at the selected destination folder. This is because playlists are also supported and things were too cluttered to have the playlist folders interspersed with the music folders. Now there will be (up to) two folders at the destination - "Music" containing all the music folders and "Playlists" containing all the playlist folders. I mention this since you've done a lot of copying already - would hate to have you accidentally create a zillion extra copies one level down.

**Comment by tattwamasi** [comment]
Great, glad to hear it.  Closing the issue.  Let me know if anything else comes up, or there's some other desperately needed feature.
